export { default as Background } from "./img/BackGround.png";
export { default as DisplayYear } from "./img/DisplayYear.png";
export { default as PANORAMA } from "./svg/PANORAMA";
export { default as THE_END } from "./img/THE_END.png";
export { default as Panorama2 } from "./img/Panorama2.png";
export { default as ProjectPageBackground } from "./img/ProjectPageBackground.png";
export { default as DisplayDate } from "./svg/DisplayDate";
export { default as DisplayDate2 } from "./svg/DisplayDate_2";
export { default as GSMGraduationExhibition } from "./svg/GSMGraduationExhibition";
